# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import user_pb2 as proto_dot_user__pb2


class HelloStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello_user = channel.unary_unary(
        '/Hello/hello_user',
        request_serializer=proto_dot_user__pb2.User.SerializeToString,
        response_deserializer=proto_dot_user__pb2.Respose.FromString,
        )


class HelloServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hello_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello_user': grpc.unary_unary_rpc_method_handler(
          servicer.hello_user,
          request_deserializer=proto_dot_user__pb2.User.FromString,
          response_serializer=proto_dot_user__pb2.Respose.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Hello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
